INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','10765678-9','Oliver','Jake','amazon','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','12343123-8','Jack','Connor','amazon','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','9878988-3','Harry','Callum','google','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','16787890-7','Jacob','Jones','google','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','20098090-6','Charlie','Williams','company star','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','203400947-7','Thomas','Smith','tecno pro','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','20938493-7','George','Connor','Oracle Corp','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','22984782-8','Harry','Davies','Intel Corp','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','18986450-0','James','Wilson','company star','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','18985349-6','William','Jones','company star','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','10980987-5','Charlie','Thomas','Intel Corp','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','22878231-8','Thomas','Roberts','Intel Corp','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','21981270-7','George','Smith','company star','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','15872564-7','Oscar','Jones','company star','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','12134987-2','James','Byrne','amazon','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','17763344-9','Harry','Williams','amazon','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','20898776-3','Oscar','Connor','amazon','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','21787980-K','James','Wilson','Intel Corp','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','15676789-6','Thomas','Evans','Intel Corp','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','20987665-K','George','Thomas','google','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','11236665-4','Jacob','Roberts','google','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','10989097-5','Alexander','Williams','google','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','16876569-2','Daniel','Connor','company star','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','16654323-7','Thomas','Connor','company star','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','16898889-8','George','Jones','amazon','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','12333451-8','Oscar','Williams','amazon','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','18672096-7','James','Brown','Intel Corp','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','22098098-5','Harry','Jake','google','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','21212133-3','Thomas','Connor','google','','','');
INSERT INTO `personas`(`autorizado`, `rut`, `nombre`, `apellidos`, `empresa`, `seccion`, `patente`, `observaciones`) VALUES ('si','13334565-6','George','Smith','google','','','');
